function [is, im, iv, out] = calc_current_distribution(j, g, p)

    % Electron/proton current-density distribution through PEMFC layers
    %
    %   [is,im,iv,out] = calc_current_distribution(j,g,p)
    %
    %   INPUT
    %   -----
    %   j : externally applied current density [A/m^2]
    %
    %   g : grid structure generated by build_grid.m
    %
    %   p : parameter structure generated by params.m
    %
    %
    %   OUTPUT
    %   ------
    %   is : electronic current density on global cell centers [A/m^2]
    %
    %   im : protonic current density on global cell centers [A/m^2]
    %
    %   iv : volumetric reaction current density [A/m^3]
    %
    %        anode CL:
    %            iv = +j / LaCL
    %
    %        cathode CL:
    %            iv = +j / LcCL
    %
    %        elsewhere:
    %            iv = 0
    %
    %
    %   out.iv_a : anodic volumetric reaction current density [A/m^3]
    %   out.iv_c : cathodic volumetric reaction current density [A/m^3]
    %   out.dimdx : signed proton-current gradient [A/m^3]
    %   out.isFace, out.imFace : current densities on cell faces [A/m^2]
    %
    %   out.currentError :
    %       max(abs(is + im - j))
    %
    %
    %   Model assumption from problem statement:
    %
    %       is + im = j
    %
    %   GDL carries electrons only.
    %   PEM carries protons only.
    %   Reaction current is uniformly distributed in each catalyst layer.
    
    %% ------------------------------------------------------------------------
    %  1. Input checks
    % -------------------------------------------------------------------------
    
    if ~isscalar(j) || ~isfinite(j)
        error('j must be a finite scalar current density.');
    end
    
    if j < 0
        error(['Current implementation assumes fuel-cell operation ', ...
               'with j >= 0.']);
    end
    
    
    %% ------------------------------------------------------------------------
    %  2. Allocate full-grid arrays
    % -------------------------------------------------------------------------
    
    is = zeros(g.N,1);
    im = zeros(g.N,1);
    iv = zeros(g.N,1);
    dimdx = zeros(g.N,1);
    
    
    %% ------------------------------------------------------------------------
    %  3. aGDL
    % -------------------------------------------------------------------------
    %
    % Electronic conductor only
    %
    
    is(g.idx_aGDL) = j;
    im(g.idx_aGDL) = 0;
    
    
    %% ------------------------------------------------------------------------
    %  4. aCL
    % -------------------------------------------------------------------------
    %
    % Uniform volumetric reaction current:
    %
    %       iv,a = j / LaCL
    %
    % Assuming:
    %
    %       d(is)/dx = -iv
    %       d(im)/dx = +iv
    %
    % with boundary condition at aGDL/aCL:
    %
    %       is = j
    %       im = 0
    %
    
    idx = g.idx_aCL;
    
    xLeft = g.layerBoundary(2);
    LaCL  = p.geom.LaCL;
    
    xi = ...
        (g.x(idx) - xLeft) ./ LaCL;
    
    % Protect against tiny floating-point excursion
    xi = min(max(xi,0),1);
    
    is(idx) = j .* (1 - xi);
    im(idx) = j .* xi;
    
    iv_a = j ./ LaCL;
    
    iv(idx) = iv_a;
    dimdx(idx) = iv_a;
    
    
    %% ------------------------------------------------------------------------
    %  5. PEM
    % -------------------------------------------------------------------------
    %
    % Protonic conductor only
    %
    
    is(g.idx_PEM) = 0;
    im(g.idx_PEM) = j;
    
    
    %% ------------------------------------------------------------------------
    %  6. cCL
    % -------------------------------------------------------------------------
    %
    % Uniform volumetric reaction current:
    %
    %       iv,c = +j / LcCL
    %
    % Protonic current decreases from j to zero;
    % electronic current increases from zero to j.
    %
    
    idx = g.idx_cCL;
    
    xLeft = g.layerBoundary(4);
    LcCL  = p.geom.LcCL;
    
    xi = ...
        (g.x(idx) - xLeft) ./ LcCL;
    
    xi = min(max(xi,0),1);
    
    is(idx) = j .* xi;
    im(idx) = j .* (1 - xi);
    
    iv_c = j ./ LcCL;
    
    iv(idx) = iv_c;
    dimdx(idx) = -iv_c;
    
    
    %% ------------------------------------------------------------------------
    %  7. cGDL
    % -------------------------------------------------------------------------
    %
    % Electronic conductor only
    %
    
    is(g.idx_cGDL) = j;
    im(g.idx_cGDL) = 0;
    
    
    %% ------------------------------------------------------------------------
    %  8. Face-current distributions
    % -------------------------------------------------------------------------
    %
    % Finite-volume water fluxes are defined on faces, so construct the
    % exact face values rather than interpolating across material interfaces.

    imFace = zeros(g.N+1,1);

    f1 = g.face_aGDL_aCL;
    f2 = g.face_aCL_PEM;
    f3 = g.face_PEM_cCL;
    f4 = g.face_cCL_cGDL;

    imFace(f1:f2) = linspace(0,j,f2-f1+1).';
    imFace(f2:f3) = j;
    imFace(f3:f4) = linspace(j,0,f4-f3+1).';

    isFace = j - imFace;


    %% ------------------------------------------------------------------------
    %  9. Diagnostics
    % -------------------------------------------------------------------------
    
    out.iv_a = iv_a;
    out.iv_c = iv_c;
    out.dimdx = dimdx;
    out.isFace = isFace;
    out.imFace = imFace;
    
    out.currentError = ...
        max(abs(is + im - j));

    out.faceCurrentError = ...
        max(abs(isFace + imFace - j));
    
    out.currentConserved = ...
        max(out.currentError,out.faceCurrentError) < ...
        max(1e-10,1e-12*max(abs(j),1));

end
