function [divJ, info] = flux_divergence_fv(Jface, g, idx)
%FLUX_DIVERGENCE_FV
% Finite-volume divergence of a face flux on a 1-D contiguous domain.
%
%   [divJ,info] = flux_divergence_fv(Jface,g,idx)
%
% Sign convention:
%
%   J > 0  means flux in the +x direction.
%
% This function returns
%
%       divJ = -dJ/dx
%
% so that a conservation equation written as
%
%       d(phi)/dt = -dJ/dx + S
%
% can directly use
%
%       dphi_dt = divJ + S
%
%
% INPUT
% -----
% Jface :
%     Flux evaluated on control-volume faces.
%     Length must be N+1 if idx contains N cells.
%
% g :
%     Grid structure generated by build_grid.m
%
% idx :
%     Global indices of the local transport domain.
%     Must form a contiguous sequence.
%
%
% OUTPUT
% ------
% divJ :
%     Finite-volume approximation of -dJ/dx
%
% info :
%     Conservation diagnostics
%
%       .Jleft
%       .Jright
%       .integralDiv
%       .boundaryNet
%       .balanceError
%       .conserved


%% ------------------------------------------------------------------------
% 1. Prepare inputs
% -------------------------------------------------------------------------

Jface = Jface(:);
idx   = idx(:);

N = numel(idx);

if N == 0
    error('flux_divergence_fv:EmptyDomain', ...
        'idx must contain at least one cell.');
end

if numel(Jface) ~= N + 1
    error('flux_divergence_fv:SizeMismatch', ...
        ['Jface must contain N+1 face values. ', ...
         'Expected %d values, received %d.'], ...
         N+1, numel(Jface));
end

if any(~isfinite(Jface))
    error('flux_divergence_fv:InvalidFlux', ...
        'Jface contains non-finite values.');
end

if idx(1) < 1 || idx(end) > g.N
    error('flux_divergence_fv:InvalidIndex', ...
        'idx lies outside the global grid.');
end

if N > 1 && any(diff(idx) ~= 1)
    error('flux_divergence_fv:NonContiguousDomain', ...
        'idx must describe a contiguous spatial domain.');
end


%% ------------------------------------------------------------------------
% 2. Cell widths
% -------------------------------------------------------------------------

dx = g.dx(idx);

if any(dx <= 0)
    error('flux_divergence_fv:InvalidGrid', ...
        'Control-volume widths must be positive.');
end


%% ------------------------------------------------------------------------
% 3. Finite-volume flux divergence
% -------------------------------------------------------------------------
%
% For cell i:
%
%       -dJ/dx
%       =
%       (J_left - J_right)/dx
%

divJ = ...
    (Jface(1:end-1) - Jface(2:end)) ./ dx;


%% ------------------------------------------------------------------------
% 4. Conservation diagnostics
% -------------------------------------------------------------------------
%
% Integral over entire local domain:
%
%   integral(-dJ/dx dx)
%       = J_left - J_right
%

info.Jleft  = Jface(1);
info.Jright = Jface(end);

info.integralDiv = ...
    sum(divJ .* dx);

info.boundaryNet = ...
    info.Jleft - info.Jright;

info.balanceError = ...
    info.integralDiv - info.boundaryNet;

tol = ...
    max(1e-12, ...
    1e-10 * max(abs(info.boundaryNet),1));

info.conserved = ...
    abs(info.balanceError) <= tol;

end