function Dw = membrane_water_diffusivity(lambda, T, p)

    % Water diffusivity in proton-exchange membrane
    %
    %   Dw = 1e-10 *
    %        exp[2416*(1/303.15 - 1/T)] *
    %        (2.563 - 0.33*lambda ...
    %               + 0.0264*lambda^2 ...
    %               - 0.000671*lambda^3)
    
    if any(T(:) <= 0)
        error('Temperature must be greater than zero.');
    end
    
    polyLambda = ...
          p.water.Dmem_c(1) ...
        + p.water.Dmem_c(2).*lambda ...
        + p.water.Dmem_c(3).*lambda.^2 ...
        + p.water.Dmem_c(4).*lambda.^3;
    
    Dw = ...
        p.water.Dmem_prefactor .* ...
        exp( ...
            p.water.Dmem_Eterm .* ...
            (1/303.15 - 1./T) ...
            ) .* ...
        polyLambda;
    
    %% Physical check
    
    if any(Dw(:) < 0)
        warning('membrane_water_diffusivity:NegativeValue', ...
            ['Membrane-water diffusivity became negative. ', ...
             'Check lambda range.']);
    end

end