function s = state(g)
%BUILD_STATE_INDEX  Build compact state-vector indexing for PEMFC model
%
%   s = build_state_index(g)
%
%   State vector:
%
%       x = [ T ;
%             cH2 ;
%             cO2 ;
%             mw ;
%             mi ]
%
%   where
%
%       T    : temperature over entire domain
%       cH2  : hydrogen concentration in aGDL + aCL
%       cO2  : oxygen concentration in cCL + cGDL
%       mw   : total water content over entire domain
%       mi   : ice mass concentration in porous regions only
%
%   INPUT
%   -----
%   g : grid structure generated by build_grid.m
%
%   OUTPUT
%   ------
%   s : state-index structure
%
%   Example
%   -------
%       p = params();
%       g = build_grid(p);
%       s = build_state_index(g);
%
%       T   = x(s.idx.T);
%       cH2 = x(s.idx.H2);
%       cO2 = x(s.idx.O2);
%       mw  = x(s.idx.mw);
%       mi  = x(s.idx.mi);
%
%   All indices are MATLAB 1-based indices.

    %% ------------------------------------------------------------------------
    %  1. Check required grid information
    % -------------------------------------------------------------------------
    
    requiredFields = { ...
        'N', ...
        'idx_H2', ...
        'idx_O2', ...
        'idx_porous', ...
        'idx_aGDL', ...
        'idx_aCL', ...
        'idx_PEM', ...
        'idx_cCL', ...
        'idx_cGDL' ...
        };
    
    for k = 1:numel(requiredFields)
    
        if ~isfield(g,requiredFields{k})
            error( ...
                'build_state_index:MissingGridField', ...
                'Grid structure g does not contain field "%s".', ...
                requiredFields{k});
        end
    
    end
    
    
    %% ------------------------------------------------------------------------
    %  2. Number of states belonging to each physical variable
    % -------------------------------------------------------------------------
    
    s.n.T   = g.N;
    
    s.n.H2  = numel(g.idx_H2);
    
    s.n.O2  = numel(g.idx_O2);
    
    s.n.mw  = g.N;
    
    s.n.mi  = numel(g.idx_porous);
    
    
    %% ------------------------------------------------------------------------
    %  3. Allocate state-vector ranges
    % -------------------------------------------------------------------------
    %
    % State ordering:
    %
    %       [ T | H2 | O2 | mw | mi ]
    %
    
    cursor = 0;
    
    
    % Temperature -------------------------------------------------------------
    
    s.idx.T = cursor + (1:s.n.T);
    
    cursor = cursor + s.n.T;
    
    
    % Hydrogen ---------------------------------------------------------------
    
    s.idx.H2 = cursor + (1:s.n.H2);
    
    cursor = cursor + s.n.H2;
    
    
    % Oxygen -----------------------------------------------------------------
    
    s.idx.O2 = cursor + (1:s.n.O2);
    
    cursor = cursor + s.n.O2;
    
    
    % Total water ------------------------------------------------------------
    
    s.idx.mw = cursor + (1:s.n.mw);
    
    cursor = cursor + s.n.mw;
    
    
    % Ice --------------------------------------------------------------------
    
    s.idx.mi = cursor + (1:s.n.mi);
    
    cursor = cursor + s.n.mi;
    
    
    % Total state-vector length ----------------------------------------------
    
    s.Nx = cursor;
    
    
    %% ------------------------------------------------------------------------
    %  4. Physical domain associated with each compact state
    % -------------------------------------------------------------------------
    %
    % These map a local state vector back to the global through-plane grid.
    %
    % Example:
    %
    %   cH2_full = NaN(g.N,1);
    %   cH2_full(s.domain.H2) = x(s.idx.H2);
    %
    
    s.domain.T  = (1:g.N).';
    
    s.domain.H2 = g.idx_H2(:);
    
    s.domain.O2 = g.idx_O2(:);
    
    s.domain.mw = (1:g.N).';
    
    s.domain.mi = g.idx_porous(:);
    
    
    %% ------------------------------------------------------------------------
    %  5. Local-to-global maps
    % -------------------------------------------------------------------------
    
    s.localToGlobal.T  = s.domain.T;
    
    s.localToGlobal.H2 = s.domain.H2;
    
    s.localToGlobal.O2 = s.domain.O2;
    
    s.localToGlobal.mw = s.domain.mw;
    
    s.localToGlobal.mi = s.domain.mi;
    
    
    %% ------------------------------------------------------------------------
    %  6. Global-grid -> local-variable maps
    % -------------------------------------------------------------------------
    %
    % Value 0 means that the variable does not exist in that global cell.
    %
    % Example:
    %
    %   s.globalToLocal.H2(i)
    %
    % gives the local H2 state number corresponding to global grid cell i.
    %
    
    s.globalToLocal.T = (1:g.N).';
    
    s.globalToLocal.mw = (1:g.N).';
    
    
    % H2 ---------------------------------------------------------------------
    
    s.globalToLocal.H2 = zeros(g.N,1);
    
    s.globalToLocal.H2(g.idx_H2) = ...
        (1:s.n.H2).';
    
    
    % O2 ---------------------------------------------------------------------
    
    s.globalToLocal.O2 = zeros(g.N,1);
    
    s.globalToLocal.O2(g.idx_O2) = ...
        (1:s.n.O2).';
    
    
    % Ice --------------------------------------------------------------------
    
    s.globalToLocal.mi = zeros(g.N,1);
    
    s.globalToLocal.mi(g.idx_porous) = ...
        (1:s.n.mi).';
    
    
    %% ------------------------------------------------------------------------
    %  7. Global-grid -> full state-vector index maps
    % -------------------------------------------------------------------------
    %
    % These are especially convenient later in debugging.
    %
    % Example:
    %
    %   stateID = s.globalToState.mi(i);
    %
    % directly returns the position in x corresponding to the ice state at
    % global cell i.
    %
    % A zero means no such state exists in that cell.
    %
    
    s.globalToState.T = s.idx.T(:);
    
    s.globalToState.mw = s.idx.mw(:);
    
    
    % Hydrogen ---------------------------------------------------------------
    
    s.globalToState.H2 = zeros(g.N,1);
    
    s.globalToState.H2(g.idx_H2) = s.idx.H2(:);
    
    
    % Oxygen -----------------------------------------------------------------
    
    s.globalToState.O2 = zeros(g.N,1);
    
    s.globalToState.O2(g.idx_O2) = s.idx.O2(:);
    
    
    % Ice --------------------------------------------------------------------
    
    s.globalToState.mi = zeros(g.N,1);
    
    s.globalToState.mi(g.idx_porous) = s.idx.mi(:);
    
    
    %% ------------------------------------------------------------------------
    %  8. Useful catalyst-layer local indices
    % -------------------------------------------------------------------------
    %
    % Later we frequently need:
    %
    %   H2 values specifically in aCL
    %   O2 values specifically in cCL
    %
    % Rather than repeatedly searching for them in pemfc_rhs, precompute here.
    %
    
    s.local.H2_aGDL = s.globalToLocal.H2(g.idx_aGDL);
    
    s.local.H2_aCL  = s.globalToLocal.H2(g.idx_aCL);
    
    s.local.O2_cCL  = s.globalToLocal.O2(g.idx_cCL);
    
    s.local.O2_cGDL = s.globalToLocal.O2(g.idx_cGDL);
    
    
    % Ice-state local indices for each porous material -----------------------
    
    s.local.mi_aGDL = s.globalToLocal.mi(g.idx_aGDL);
    
    s.local.mi_aCL  = s.globalToLocal.mi(g.idx_aCL);
    
    s.local.mi_cCL  = s.globalToLocal.mi(g.idx_cCL);
    
    s.local.mi_cGDL = s.globalToLocal.mi(g.idx_cGDL);
    
    
    %% ------------------------------------------------------------------------
    %  9. State-vector block boundaries
    % -------------------------------------------------------------------------
    %
    % Mainly useful for displaying / debugging state layout.
    %
    
    s.block.T  = [s.idx.T(1),  s.idx.T(end)];
    s.block.H2 = [s.idx.H2(1), s.idx.H2(end)];
    s.block.O2 = [s.idx.O2(1), s.idx.O2(end)];
    s.block.mw = [s.idx.mw(1), s.idx.mw(end)];
    s.block.mi = [s.idx.mi(1), s.idx.mi(end)];
    
    
    %% ------------------------------------------------------------------------
    %  10. Labels
    % -------------------------------------------------------------------------
    
    s.names = {'T','H2','O2','mw','mi'};
    
    
    %% ------------------------------------------------------------------------
    %  11. Sanity checks
    % -------------------------------------------------------------------------
    
    allIdx = [ ...
        s.idx.T, ...
        s.idx.H2, ...
        s.idx.O2, ...
        s.idx.mw, ...
        s.idx.mi ];
    
    if numel(unique(allIdx)) ~= s.Nx
        error( ...
            'build_state_index:DuplicateIndex', ...
            'Duplicate entries found in state-vector indexing.');
    end
    
    if ~isequal(sort(allIdx),1:s.Nx)
        error( ...
            'build_state_index:NonContinuousIndex', ...
            'State-vector indices are not continuous from 1 to Nx.');
    end
    
    if any(s.domain.H2 < 1 | s.domain.H2 > g.N)
        error('Invalid H2 domain indices.');
    end
    
    if any(s.domain.O2 < 1 | s.domain.O2 > g.N)
        error('Invalid O2 domain indices.');
    end
    
    if any(s.domain.mi < 1 | s.domain.mi > g.N)
        error('Invalid ice-domain indices.');
    end

end
