function verification = run_q2_linear_comparison()
%RUN_Q2_LINEAR_COMPARISON Reproduce both linear curves without a checkpoint.
% Both runs use the same five-cell quick grid, physics and solver settings.
% The optimized point is an observed, previously verified search result;
% this function does not claim to re-run the optimization algorithm.
codeDir=fileparts(mfilename('fullpath'));
addpath(codeDir);
simOpt=q2_optimization_options();
simOpt.RelTol=5e-5;
simOpt.AbsTol=5e-9;
initialTemperatureC=-10;

% Physical strategies: baseline (0.02, 0.01, 0.40) and the saved best.
baselineX=[0.02/0.50,(0.01-0.001)/0.049, ...
    (0.40-0.02)/(0.50-0.02)];
optimizedX=[0.2352824905186994,0.14447750181347999, ...
    0.86180050462795932];

fprintf('\nBaseline linear loading: real five-cell simulation.\n');
baselineWallClock=tic;
baseline=q2_evaluate_real(baselineX,'linear',initialTemperatureC,simOpt);
baselineWallS=toc(baselineWallClock);

fprintf('\nOptimized linear loading: real five-cell simulation.\n');
optimizedWallClock=tic;
optimized=q2_evaluate_real(optimizedX,'linear',initialTemperatureC,simOpt);
optimizedWallS=toc(optimizedWallClock);

verification=struct('baseline',baseline,'optimized',optimized, ...
    'simOpt',simOpt,'initialTemperatureC',initialTemperatureC, ...
    'baselineWallS',baselineWallS,'optimizedWallS',optimizedWallS, ...
    'previousObservedTimeS',40.726546388);
verification.improvementS=baseline.startup_time-optimized.startup_time;
verification.improvementPercent=100*verification.improvementS/ ...
    baseline.startup_time;
verification.repeatDifferenceS=optimized.startup_time- ...
    verification.previousObservedTimeS;
verification.passed=baseline.success && optimized.success && ...
    ~baseline.solver_failed && ~optimized.solver_failed && ...
    optimized.V_min>=simOpt.minimumVoltageV && ...
    optimized.q_use<=simOpt.qMaxCcm2 && ...
    optimized.ice_start<=simOpt.maximumIceVolumeFraction && ...
    optimized.raw.maximumPoreOccupancy<=simOpt.maximumPoreOccupancy && ...
    verification.improvementS>0;

resultPath=fullfile(codeDir,'q2_linear_comparison_result.mat');
save(resultPath,'verification','-v7.3');
fprintf('\nBASELINE %.9f s; OPTIMIZED %.9f s; gain %.9f s (%.3f%%)\n', ...
    baseline.startup_time,optimized.startup_time, ...
    verification.improvementS,verification.improvementPercent);
fprintf('Vmin=%.6f V; charge=%.6f C/cm2; ice at startup=%.6f; passed=%d\n', ...
    optimized.V_min,optimized.q_use,optimized.ice_start, ...
    verification.passed);
fprintf('Simulation time above is NOT the computer run time.\n');
assert(verification.passed,'Q2:ComparisonFailed', ...
    'A strategy failed or an optimized constraint was violated.');
plot_q2_literature_verification(resultPath, ...
    fullfile(codeDir,'q2_linear_comparison.png'));
end
