function verification = verify_q2_literature_best(reportPath,outputPath)
%VERIFY_Q2_LITERATURE_BEST Re-run baseline and saved incumbent on SAME grid.
% No optimization cutoff, cache reuse, physical retuning, or full-grid run.
codeDir=fileparts(mfilename('fullpath'));
if nargin<1 || isempty(reportPath)
    reportPath=fullfile(codeDir,'q2_furbo_latest_report.mat');
end
if nargin<2 || isempty(outputPath)
    outputPath=fullfile(codeDir,'q2_literature_verification.mat');
end
saved=load(reportPath,'report');
report=saved.report;
assert(~isempty(report.bestX) && report.best.success, ...
    'There is no successful observed incumbent to verify.');
simOpt=q2_optimization_options();
simOpt.RelTol=report.simOpt.RelTol;
simOpt.AbsTol=report.simOpt.AbsTol;
assert(isequaln(simOpt,report.simOpt), ...
    'Saved optimization and current simulation options differ. Re-optimize first.');
if isfield(report,'sourceFiles') && isfield(report,'sourceStamp')
    for k=1:numel(report.sourceFiles)
        info=dir(fullfile(codeDir,report.sourceFiles{k}));
        assert(isscalar(info) && ...
            isequaln([info.bytes,info.datenum],report.sourceStamp(k,:)), ...
            'A tracked physical-model source changed after optimization.');
    end
end
baselineX=[0.02/0.50,(0.01-0.001)/0.049,(0.4-0.02)/(0.50-0.02)];
fprintf('\nVerification: original linear baseline, no cache or BO cutoff.\n');
wall=tic;
baseline=q2_evaluate_real(baselineX,'linear', ...
    report.initialTemperatureC,simOpt);
baselineWall=toc(wall);
fprintf('\nVerification: optimized incumbent, no cache or BO cutoff.\n');
wall=tic;
optimized=q2_evaluate_real(report.bestX,'linear', ...
    report.initialTemperatureC,simOpt);
optimizedWall=toc(wall);
verification=struct('baseline',baseline,'optimized',optimized, ...
    'simOpt',simOpt,'initialTemperatureC',report.initialTemperatureC, ...
    'baselineWallS',baselineWall,'optimizedWallS',optimizedWall, ...
    'previousObservedTimeS',report.bestTimeS, ...
    'savedAt',char(datetime('now')));
verification.improvementS=baseline.startup_time-optimized.startup_time;
verification.improvementPercent=100*verification.improvementS/baseline.startup_time;
verification.repeatDifferenceS=optimized.startup_time-report.bestTimeS;
verification.passed=baseline.success && optimized.success && ...
    ~baseline.solver_failed && ~optimized.solver_failed && ...
    optimized.V_min>=simOpt.minimumVoltageV && ...
    optimized.q_use<=simOpt.qMaxCcm2 && ...
    optimized.ice_start<=simOpt.maximumIceVolumeFraction && ...
    optimized.raw.maximumPoreOccupancy<=simOpt.maximumPoreOccupancy && ...
    verification.improvementS>0 && abs(verification.repeatDifferenceS)<0.01;
save(outputPath,'verification','-v7.3');
fprintf('BASELINE %.9f s; OPTIMIZED %.9f s; SAVED %.9f s (%.5f%%)\n', ...
    baseline.startup_time,optimized.startup_time, ...
    verification.improvementS,verification.improvementPercent);
fprintf('Vmin=%.9f V; charge=%.9f C/cm2; ice_start=%.9f; ice_peak=%.9f; pore=%.9f\n', ...
    optimized.V_min,optimized.q_use,optimized.ice_start, ...
    optimized.ice_peak,optimized.raw.maximumPoreOccupancy);
fprintf('Same-grid repeat difference=%.9g s; passed=%d\n', ...
    verification.repeatDifferenceS,verification.passed);
disp(optimized.strategy);
assert(verification.passed,'Q2:VerificationFailed', ...
    'Verification failed; inspect the saved trajectories and diagnostics.');
end
