function summary = q3_finalize_min_energy()
% Independently verify the lowest-energy archived candidates and fill Q3 table.
    codeDir = fileparts(mfilename('fullpath'));
    outDir = fullfile(codeDir,'results');
    cfg = q3_optimization_config('smoke');
    opt = cfg.simOpt;
    opt.RelTol = 1e-5;
    opt.AbsTol = 1e-9;
    opt.MaxStep = 0.025;
    opt.plot = false;
    opt.verbose = false;
    modes = {'preheat','coheat'};
    rows = cell(2,1);
    audits = cell(2,1);
    for i = 1:2
        mode = modes{i};
        archive = load(fullfile(outDir,['q3_min_energy_' mode '.mat']),'run');
        best = archive.run.best;
        assert(~isempty(best),'No feasible candidate for %s.',mode);
        th = best.thRequestedS;
        opt.tMax = max(th,1e-6);
        if strcmp(mode,'coheat'), opt.tMax = max(opt.tMax,65); end
        result = pemfc_stack5_simulate_q3(mode,best.q,th,opt);
        assert(result.success,'Tight recheck failed for %s.',mode);
        assert(all(result.auxiliaryEnergyJCell >= 0));
        assert(abs(sum(result.auxiliaryEnergyJCell)- ...
            result.totalAuxiliaryEnergyJ) < 1e-7);
        audits{i} = result;
        rows{i} = {string(mode),best.q(1),best.q(2),best.q(3), ...
            best.q(4),best.q(5),th,result.actualHeatingTimeS, ...
            result.auxiliaryEnergyJCell(1), ...
            result.auxiliaryEnergyJCell(2), ...
            result.auxiliaryEnergyJCell(3), ...
            result.auxiliaryEnergyJCell(4), ...
            result.auxiliaryEnergyJCell(5), ...
            result.totalAuxiliaryEnergyJ,result.successTimeS, ...
            result.minimumCellVoltageV,result.maximumIceVolumeFraction, ...
            max(result.maxIceVolumeFractionCell(:,[1 5]),[],'all'), ...
            max(result.maxIceVolumeFractionCell(:,3)), ...
            result.chargeUsedCcm2,result.success, ...
            numel(archive.run.history)};
    end
    rowData = vertcat(rows{:});
    names = {'mode','q1','q2','q3','q4','q5', ...
        'thRequestedS','thUsedS','E1J','E2J','E3J','E4J','E5J', ...
        'ETotalJ','startupTimeS','minimumVoltageV', ...
        'maximumIceVolumeFraction','endCellMaxIce', ...
        'centerCellMaxIce','chargeCcm2','success', ...
        'evaluations'};
    summary = table(string(rowData(:,1)),'VariableNames',{'mode'});
    for j = 2:numel(names)
        summary.(names{j}) = cell2mat(rowData(:,j));
    end
    summary.Properties.Description = ...
        'Best feasible energy candidates found; no global optimum proof.';
    writetable(summary,fullfile(outDir,'q3_final_energy_table.csv'), ...
        'Encoding','UTF-8');
    save(fullfile(outDir,'q3_final_energy_table.mat'), ...
        'summary','audits','cfg','-v7.3');
    disp(summary);
end
