function candidate = q3_joint_probe(index)
% Deliberately varied power allocations plus independent early heater stops.
    designs = [ ...
        1 1 1 1 1 24; ...
        1 .8 .5 .8 1 28; ...
        1 .5 .2 .5 1 34; ...
        .8 .8 .8 .8 .8 28; ...
        1 1 1 1 1 30.2237662556899; ...
        1 .7 .3 .7 1 30; ...
        1 .4 0 .4 1 40; ...
        .6 .8 1 .8 .6 32; ...
        1 .85 .7 .85 1 3770/(25*4.4); ...
        1 .6 .2 .6 1 3770/(25*3.4); ...
        .8 .8 .8 .8 .8 3770/(25*4); ...
        1 1 0 1 1 3770/(25*4)];
    assert(index>=1 && index<=size(designs,1));
    q = designs(index,1:5);
    th = designs(index,6);
    cfg = q3_optimization_config('smoke');
    cfg.simOpt.RelTol = 1e-5;
    cfg.simOpt.AbsTol = 1e-9;
    candidate = q3_evaluate_energy6('coheat',q,th,cfg.simOpt);
    outDir = fullfile(fileparts(mfilename('fullpath')),'results');
    path = fullfile(outDir,sprintf('q3_joint_probe_%02d.mat',index));
    save(path,'candidate','-v7.3');
    row = table(index,q(1),q(2),q(3),q(4),q(5),th, ...
        string(candidate.status),candidate.energyJ,candidate.startupTimeS, ...
        candidate.minimumVoltageV,candidate.maxIce,candidate.chargeCcm2, ...
        candidate.elapsedS,candidate.attempts,string(candidate.reason), ...
        'VariableNames',{'index','q1','q2','q3','q4','q5','th', ...
        'status','energyJ','startupTimeS','minimumVoltageV','maxIce', ...
        'chargeCcm2','elapsedS','attempts','reason'});
    writetable(row,fullfile(outDir,sprintf('q3_joint_probe_%02d.csv',index)), ...
        'Encoding','UTF-8');
    disp(row);
end
